version: '3'
services:
  prisma:
    image: 'prismagraphql/prisma:1.34'
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: ${PRISMA_MANAGEMENT_API_SECRET}
        port: 4466
        databases:
          default:
            connector: mongo
            uri: ${DB_URI}
  redis:
    image: redis
    container_name: gql_cache
    restart: always
    ports:
      - '6379:6379'
  pcengine:
    container_name: ag_pcengine
    restart: always
    ports:
      - '4000:4000'
    build: .
    env_file:
      - '.env.${ENV-production}'
    environment:
      - 'NODE_ENV=${ENV-production}'
      - PRISMA_ENDPOINT=prisma
    depends_on:
      - prisma
      - redis
