version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        managementApiSecret: ${PRISMA_MANAGEMENT_API_SECRET}
        databases:
          default:
            connector: mongo
            uri: >-
              ${DB_URI}
  pcengine:
    container_name: ag_pcengine
    restart: always
    ports:
    - "4000:4000"
    build: .
    volumes:
      - .:/opt/pcengine
      - /opt/pcengine/node_modules
    env_file:
      - .env.${ENV-production}
    environment:
      - NODE_ENV=${ENV-production}
    depends_on:
      - prisma
